---
baseurl: "/thirtydaysjourneynew" # the subpath of your site, e.g. /blog
url: "http://jtemporal.com"
name: 30 days yoga journey
description: A diary of a 30 days yoga journey
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: wowthemesnet@gmail.com
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  jess:
    name: Jess Temporal
    site: https://jtemporal.com
    avatar: "/assets/images/avatar2.jpg"
    bio: hi!
    email: hello@jtemporal.com
    twitter: https://twitter.com/jesstemporal
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: jess
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
